CREATE TYPE payment_status AS ENUM ('created', 'authorized', 'captured', 'failed', 'refunded', 'partially_refunded');
CREATE TYPE credit_entry_type AS ENUM ('purchase', 'reservation', 'consumption', 'release', 'refund', 'admin_adjustment', 'promotion');
CREATE TYPE asset_type AS ENUM ('source_selfie', 'generated_image', 'comic_panel', 'comic_pdf', 'thumbnail');
CREATE TYPE webhook_status AS ENUM ('received', 'processed', 'ignored', 'failed');

CREATE TABLE payment_orders (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES users(id), provider VARCHAR(30) NOT NULL DEFAULT 'razorpay', provider_order_id VARCHAR(100) NOT NULL UNIQUE, receipt VARCHAR(100) NOT NULL UNIQUE, amount_paise BIGINT NOT NULL CHECK(amount_paise > 0), currency CHAR(3) NOT NULL DEFAULT 'INR', credits_purchased INTEGER NOT NULL DEFAULT 1 CHECK(credits_purchased > 0), status payment_status NOT NULL DEFAULT 'created', selected_module module_type, metadata JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE payments (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), payment_order_id UUID NOT NULL REFERENCES payment_orders(id), user_id UUID NOT NULL REFERENCES users(id), provider_payment_id VARCHAR(100) NOT NULL UNIQUE, provider_signature TEXT, amount_paise BIGINT NOT NULL, currency CHAR(3) NOT NULL DEFAULT 'INR', status payment_status NOT NULL, raw_metadata JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE generation_jobs (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES users(id), module module_type NOT NULL, status generation_status NOT NULL DEFAULT 'created', idempotency_key VARCHAR(255) NOT NULL, source_asset_id UUID, input JSONB NOT NULL DEFAULT '{}'::jsonb, output JSONB NOT NULL DEFAULT '{}'::jsonb, error_code VARCHAR(100), error_message TEXT, started_at TIMESTAMPTZ, completed_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(user_id, idempotency_key));
CREATE TABLE credit_ledger (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES users(id), entry_type credit_entry_type NOT NULL, quantity INTEGER NOT NULL CHECK(quantity <> 0), payment_id UUID REFERENCES payments(id), generation_job_id UUID REFERENCES generation_jobs(id), idempotency_key VARCHAR(255) NOT NULL UNIQUE, description TEXT, metadata JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE assets (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES users(id), generation_job_id UUID REFERENCES generation_jobs(id), asset_type asset_type NOT NULL, storage_provider VARCHAR(30) NOT NULL DEFAULT 's3', bucket VARCHAR(100) NOT NULL, object_key TEXT NOT NULL UNIQUE, original_filename TEXT, mime_type VARCHAR(100) NOT NULL, size_bytes BIGINT, width INTEGER, height INTEGER, sha256 CHAR(64), metadata JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
ALTER TABLE generation_jobs ADD CONSTRAINT generation_jobs_source_asset_fk FOREIGN KEY(source_asset_id) REFERENCES assets(id);
CREATE TABLE webhook_events (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), provider VARCHAR(30) NOT NULL, provider_event_id VARCHAR(150) NOT NULL, payload_sha256 CHAR(64) NOT NULL, payload JSONB NOT NULL, status webhook_status NOT NULL DEFAULT 'received', processed_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(provider, provider_event_id));
CREATE TABLE audit_logs (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), actor_user_id UUID REFERENCES users(id), action VARCHAR(100) NOT NULL, resource_type VARCHAR(100) NOT NULL, resource_id UUID, metadata JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX credit_ledger_user_created_idx ON credit_ledger(user_id, created_at);
CREATE INDEX generation_jobs_user_created_idx ON generation_jobs(user_id, created_at DESC);
